//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RealEstate
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class nedvizhEntities1 : DbContext
    {
        public nedvizhEntities1()
            : base("name=nedvizhEntities1")
        {
        }
        private static nedvizhEntities1 _context = new nedvizhEntities1();

        public static nedvizhEntities1 GetContext()
        {
            if (_context == null)
                _context = new nedvizhEntities1();
            return _context;
        }
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Address> Address { get; set; }
        public virtual DbSet<Client> Client { get; set; }
        public virtual DbSet<Commission> Commission { get; set; }
        public virtual DbSet<Object_Nedv> Object_Nedv { get; set; }
        public virtual DbSet<Potrebnost> Potrebnost { get; set; }
        public virtual DbSet<Predlojenie> Predlojenie { get; set; }
        public virtual DbSet<Rieltor> Rieltor { get; set; }
        public virtual DbSet<Sdelka> Sdelka { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Type_Object> Type_Object { get; set; }
    }
}
