//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RealEstate
{
    using System;
    using System.Collections.Generic;
    
    public partial class Object_Nedv
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Object_Nedv()
        {
            this.Predlojenie = new HashSet<Predlojenie>();
        }
    
        public int id { get; set; }
        public int id_type { get; set; }
        public string city { get; set; }
        public Nullable<int> id_address { get; set; }
        public Nullable<int> num_house { get; set; }
        public Nullable<int> num_kv { get; set; }
        public string shirina { get; set; }
        public string dolgota { get; set; }
        public double area { get; set; }
        public Nullable<int> rooms { get; set; }
        public Nullable<int> floor { get; set; }
    
        public virtual Address Address { get; set; }
        public virtual Type_Object Type_Object { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Predlojenie> Predlojenie { get; set; }
    }
}
